[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.116.1",
    "langchain[google-genai]>=0.3.27",
    "python-dotenv>=1.1.1",
    "uvicorn>=0.35.0",
]
