from typing import List, Optional

from langchain.tools import tool


@tool
def schedule_meeting(
    Attendies: List[str], body: str, start_time: str, end_time: str
):  
    # Google oauth to set up calendar API
    """
    Schedule metting using google's calender API

    Attendies(List(str)): List of attendies
    body(str): summary generated by the llm
    start_time(str): meeting start time (need to figure out how timming it would work)
    end_time(str): meeting end time
    """
    pass
